openapi: 3.0.0
info:
  title: Herarchy API
  description: Hierarchy items API
  version: 1.0.0

paths:
  /hierarchy:
    get:
      $ref: './endpoints/items.yaml#/getRoot'

    post:
      $ref: './endpoints/items.yaml#/createItem'

  /hierarchy/{itemId}:
    get:
      $ref: './endpoints/items.yaml#/getItem'

    delete:
      $ref: './endpoints/items.yaml#/deleteItem'

  /auth:
    post:
      $ref: './endpoints/auth.yaml#/login'
